id: PD6ECDD50
initial_creation_type: input
source_metadata:
  title: Sāṃkhyasūtra including the Tattvasamāsa, an abstract of Sāṃkhya philosophy
    (appended at the end)
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Philosophy -- Sāṃkhya
  data entry: members of the Sansknet Project
  contribution to GRETIL: members of the Sansknet Project
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T14:59:49.551240'
last_modified_at: '2022-03-09T14:59:49.551253'
